config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "tasks", to: "tasks#index"
  # get "tasks/new", to:"tasks#new"
  # post "tasks", to:"tasks#create"
  # get "tasks/:id", to:"tasks#show" , as: 'task'
  # get "tasks/:id/edit", to:"tasks#edit"
  # patch "tasks/:id", to:"tasks#update"
  # delete "tasks/:id", to:"tasks#destroy"

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to task_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
    <%= f.label :completed %>
    <%= f.text_field :completed, class: 'form-control'  %>

    <%= f.submit "Update Task", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<div class="container">
  <div class="page-header">
    <h1>My tasks</h1>
  </div>
  <hr class="border border-danger border-2 opacity-50">
  <% @tasks.each do |task| %>
      <p><%= link_to task.title , task_path(task)%></p>
  <% end %>
  <%= link_to "Add new task", new_task_path, class: "btn btn-secondary"%>
</div>

app/views/tasks/new.html.erb
<%= form_with model: @task do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'form-label' %>
    <%= f.text_field :title, class: 'form-control' %>
    <br>
    <%= f.label :details, class: 'form-label' %>
    <%= f.text_field :details, class: 'form-control' %>
    <br>
    <%= f.label :completed, class: 'form-label' %>
    <%= f.text_field :completed, class: 'form-control' %>
    <br>
    <%= f.submit "Create Task", class: 'btn btn-success'%>
  </div>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title%></h2>
<p><%= @task.details%></p>
<p><%= @task.completed%></p>
<%= link_to "Delete", task_path(@task),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>